### ISSUE TITLE
Can't Kill Creep

### ISSUE THREAD

**Issue by ahkui** [Praytic/youtd2#108]
<img width="960" alt="image" src="https://github.com/Praytic/youtd2/assets/14049597/2bce54fc-bc2b-4bb4-bdf2-f39cdfbdc91e">

**Comment by ahkui** [comment]
<img width="960" alt="image" src="https://github.com/Praytic/youtd2/assets/14049597/43414c1b-f493-458e-812c-23becdc36a5f">

**Comment by ahkui** [comment]
<img width="960" alt="image" src="https://github.com/Praytic/youtd2/assets/14049597/2176e8da-a926-400e-aef1-27cb158d3c17">

**Comment by Kvel2D** [comment]
Thanks for finding this bug!

The problem was that creeps with multiple specials got their max hp reduced too much and the combat system couldn't process max hp of 0 correctly.

Change max hp so that it never goes below 1.

Also fixed wave specials so that they don't reduce creep hp too much when there are multiple specials on a creep:
acd1a625c8d7bebd33689876fa931e32d9d6f1b1
