### ISSUE TITLE
Expand BottomMenuBar to fully fit at least 4 UnitButtons on each side

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#253]
Also add a small indicator showing that more UnitButtons can be scrolled to the right or left in the stash.

**Comment by Leiyiliro** [comment]
Hey, first of all, thanks for all the hard work you are putting into this!

If I may suggest one thing, maybe adding some "+" buttons on each side of the bar so that the player can increase the slots to some reasonable limit (maybe 6-10 whatever feals good) in either direction. 
There are 2 reasons for this:
1. The autosuggestions in the Horadric cube are not always the best (some items are very good even on lower rarity) and it's a bit hard to search for what items to combine when you need to scroll a lot once you acumulate a lot of items.
2. Situational items, that you may want to swap depending on the wave on the carry towers. It would be great if there was another stash where you could put those or some other easily accesible way to reach those, or maybe some way to pin them to the start of the bar so find them easily. In the original game I usually kept them on my builder, or had a "storage" tower for those.

**Comment by Kvel2D** [comment]
Closing this because tower stash and item stash have been reworked and this issue is not relevant anymore.

Moved feature suggestion to #362
