### ISSUE TITLE
When item was returned back to stash, it should appear at the end of the list

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#334]
When item is picked up first time - it should always appear at the start of the list.

**Comment by Kvel2D** [comment]
Pros/cons for adding items to beginning of item stash:
+ If there are many items and player needs to scroll to see the end, then item added to beginning will be more visible to player..
- Adding an item to beginning shifts all other items. If player was about to click on an item, they may misclick due to this shift.
- The shift looks weird visually.

The cons outweight the pros. Also, recently I increased the amount of visible items so the one pro is not as important as it used to be.
