### ISSUE TITLE
Always allow to enter tower placement mode

### ISSUE THREAD

**Issue by basxto** [Praytic/youtd2#359]
Currently it is not possible to start placing a tower if you can’t afford it. 
But…
* it would be nice to see the range of a tower and whether it’s worth saving for it
* if there is only 2 food left, you can’t upgrade a 2 food tower to a 4 food tower.

That should be better handled per cell, by tinting the tower red if it can’t be placed.

**Comment by Praytic** [comment]
It is usually not allowed in any game to "preview" a tower if you can't afford it. This mechanic can confuse new players. Typically, when you press the tower icon, you receive a warning that you can't afford the tower. Imagine not receiving this warning and instead beginning to drag the tower into the building area. Only after you've found the place where you want to place it, do you receive a warning that the requirements are not met. At first, you might think this is a bug, because you were able to select the tower and drag its preview across the map.

**Comment by basxto** [comment]
The bigger problem are tower upgrades, the game does not allow to place tower upgrades even if they are affordable. And the actual price is only known when you want to place the tower. If I have only 2 food left and want to upgrade a 2 food tower to a 4 food tower I currently need to sell that tower despite being able to afford it. Even with 0 food left you could upgrade a 2 food tower to another 2 food tower. In these scenarios you are forced to sell the tower and lose experience. It’s different when you don’t have enough gold, there wouldn’t be any case where you could afford it.

> Only after you've found the place where you want to place it, do you receive a warning that the requirements are not met.

In that scenario the tower should be tinted red if it can’t be afforded like with overlaps. Maybe a crossed out food icon is needed on positions where you don’t have enough food to place a tower. And maybe a warning that the player only has enough food for upgrades.

**Comment by Kvel2D** [comment]
Moved to Suggestions https://github.com/Praytic/youtd2/discussions/409

**Comment by Kvel2D** [comment]
Never mind, reopening because moving this stuff to discussions is a bad idea.

**Comment by Kvel2D** [comment]
In version 0.18.0 it is now possible to start building a tower if food requirement is not met.

This solves the issue of not being able to transform for this scenario "if there is only 2 food left, you can’t upgrade a 2 food tower to a 4 food tower." and others.

I decided against allowing to start building a tower if gold/tome requirements are not met. It is important to give feedback 
to player if those requirements are not met *before* starting to build, not at the moment when player tries to place the tower.

It would be a frustrating experience for the player to:
- forget to check current gold/tomes vs tower costs
- start to build a tower
- move mouse to build position
- see an error about gold/tome requirements

For food cost this is less critical because food usage stays below max value during the beginning, reaches max value and then stays at max value until the end of the game.
