### ISSUE TITLE
Dangling reference in select_unit.gd

### ISSUE THREAD

**Issue by PiotrKaszuba** [Praytic/youtd2#469]
During one of the games I've had following situation happen:
- I was playing from Godot in debugging mode
- Randomly on wave about 290~ such error was caught - it seems that `_units_under_mouse_list` contains null. Not sure how that happened - not sure if it could be due to very rare occurence with memory being freed.. or some other bug that caused it.
- I believe that the error on null  doesn't allow the local code to continue and is probably caught somewhere else (in the engine?) when continuing runtime.
- The error persists: I was able to continue runtime but whenever I hovered over any unit same error was caught and the  `_units_under_mouse_list` now contained 2 entries (screenshot shows initial occurence with only 1 entry) with null at 0 index and some probably valid object at index 1. The local code selects the 0th index and crashes again. My guess is the null at 0th index never goes away.
- When I've stopped suspending the execution on error in the debugger: the game continued but I was locked out of selecting any unit. I wasn't even able to drop an item/oil onto the tower. However, I was able to interact with items - drag them, move in stash etc.
- I'm not sure if some deeper issue should be solved here, or if the local code to this error occuring should just check whether `_units_under_mouse_list` contains null and remove it..
- I've played on the branch of this PR #462 which at the moment is [10 commits ahead of](https://github.com/PiotrKaszuba/youtd2/compare/Praytic%3Ayoutd2%3Amain...items_qol), [21 commits behind](https://github.com/PiotrKaszuba/youtd2/compare/items_qol...Praytic%3Ayoutd2%3Amain) Praytic/youtd2:main - at commit https://github.com/PiotrKaszuba/youtd2/commit/a76d27641e79b7b88e43d813ef7d173718a80cb8
- However, I don't believe this branch could have caused this particular error as the work there is related to items and stashes.
![error](https://github.com/user-attachments/assets/792d831b-c746-44b3-b019-bbf5d3707217)

**Comment by Kvel2D** [comment]
I've managed to reproduce a similar, but not exactly the same, issue.

1. Build a tower
2. Spawn boss wave
3. Select boss
4. Deselect boss with Escape, keep hovering over boss
5. Wait for tower to kill boss
6. Now _units_under_mouse_list Array contains a dangling reference. Moving a mouse causes a breakpoint, also waiting for next creep to go under mouse causes a breakpoint.

![2024-10-09 21_19_47-title_screen tscn - YouTD 2 - Godot Engine](https://github.com/user-attachments/assets/81604f75-6a5c-4202-af02-1a3f1fae86f4)

The issue is with `_on_unit_tree_exited()` callback which is supposed to clear references when creeps die. It's used for both selection and hovering. Selection code in `set_selected_unit()` disconnects that callback, without considering whether it is still needed for hovering logic.

This issue is not exactly the same as the originally reported one, so there may be more deeper issues. For now, will fix the reproducible issue and add brute force check for valid references.

**Comment by PiotrKaszuba** [comment]
Thank you. The reproducible issue seems about the same without the first occurence of error that I've shown on the screen- the following occurences stopped at the exactly same point - when sorting and with similar contents of `_units_under_mouse_list`. The reason for that would be no sorting actually took place the first time as that Array had only 1 element.

**Comment by Kvel2D** [comment]
I added a fix but need to double check the original issue.
It might be different because my reproduced issue also had null SelectUnit._hovered_unit.

**Comment by PiotrKaszuba** [comment]
> also had null SelectUnit._hovered_unit

I think the same is the case for my case - I captured all local and member variables in the picture.

**Comment by Kvel2D** [comment]
In your  case, you had `_hovered_unit == "true null"`.
In my case, _hovered_unit was a "previously freed reference", but displayed as "null" in editor.

I couldn't find any other issues which might cause dangling references in SelectUnit, so will close. The fix in dc36acf5c946e44b3ed5d5882729d424b85ab256 most likely solves both issues.

**Comment by PiotrKaszuba** [comment]
Thank you. I didn't know the difference between those null values nor I was able to spot it.
